# Generated by Django 3.2.7 on 2022-01-01 07:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_sitesupporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(max_length=256)),
                ('text', ckeditor.fields.RichTextField(max_length=4056)),
                ('url', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='is_promote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organ',
            name='is_promote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_promote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirements',
            name='is_promote',
            field=models.BooleanField(default=False),
        ),
    ]
