# Generated by Django 3.2.7 on 2022-01-01 07:52

import ckeditor.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220101_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organ',
            name='category',
        ),
        migrations.RemoveField(
            model_name='organ',
            name='group',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fax',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='interface_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='interface_phone_number',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tel_channel',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='address',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='established_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='info/file'),
        ),
        migrations.AlterField(
            model_name='info',
            name='introduction_of_a_company',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='website',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='news/video'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='activity_type',
            field=ckeditor.fields.RichTextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='organ',
            name='info',
            field=ckeditor.fields.RichTextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='organ',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization/logo'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='applicant_entity_logo',
            field=models.ImageField(blank=True, null=True, upload_to='requirements/applicant_entity_image'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='requirements/file'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='requirements/image'),
        ),
        migrations.AlterField(
            model_name='sitesupporter',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2056, null=True),
        ),
        migrations.AlterField(
            model_name='standards',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, max_length=128, null=True),
        ),
    ]
