# Generated by Django 3.2.7 on 2022-01-01 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220101_0752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='company',
            new_name='organ',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='company',
            new_name='organ',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='company',
            new_name='organ',
        ),
        migrations.RenameField(
            model_name='standards',
            old_name='company',
            new_name='organ',
        ),
    ]
