# Generated by Django 3.2.7 on 2022-01-01 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220101_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organ',
            old_name='galley',
            new_name='gallery',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='galley',
            new_name='gallery',
        ),
    ]
