# Generated by Django 3.2.7 on 2022-01-01 13:27

import blog.models_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220101_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='media',
            field=models.FileField(upload_to='gallery/logo', validators=[blog.models_validators.validate_video_extension, blog.models_validators.validate_img_extension]),
        ),
        migrations.AlterField(
            model_name='news',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='news/video', validators=[blog.models_validators.validate_video_extension, blog.models_validators.validate_img_extension]),
        ),
    ]
