# Generated by Django 3.2.7 on 2022-01-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220101_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='src',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
