# Generated by Django 3.2.7 on 2022-01-01 13:29

import blog.models_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220101_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AlterField(
            model_name='news',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='news/media', validators=[blog.models_validators.validate_video_extension, blog.models_validators.validate_img_extension]),
        ),
    ]
