# Generated by Django 3.2.7 on 2022-01-18 14:07

import blog.models_validators
import ckeditor.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_news_src'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'تماس با ما', 'verbose_name_plural': 'مجموعه تماس با ما'},
        ),
        migrations.AlterModelOptions(
            name='galery',
            options={'verbose_name': 'گالری', 'verbose_name_plural': 'گالری ها'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'گروه', 'verbose_name_plural': 'گروه ها'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'اطلاعات ارگان', 'verbose_name_plural': 'اطلاعات ارگان ها'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'خبر', 'verbose_name_plural': 'اخبار'},
        ),
        migrations.AlterModelOptions(
            name='organ',
            options={'verbose_name': 'ارگان', 'verbose_name_plural': 'ارگان ها'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'صفحه شخصی شده', 'verbose_name_plural': 'مجموعه صفحات شخصی سازی شده'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='requirements',
            options={'verbose_name': 'نیازمندی', 'verbose_name_plural': 'نیازمندی ها'},
        ),
        migrations.AlterModelOptions(
            name='sitesupporter',
            options={'verbose_name': 'حامی سایت', 'verbose_name_plural': 'حامیان سایت'},
        ),
        migrations.AlterModelOptions(
            name='standards',
            options={'verbose_name': 'استاندارها', 'verbose_name_plural': 'استاندارهای '},
        ),
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.group', verbose_name='گروه'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=512, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=512, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fax',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='فکس'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='interface_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='نام رابط'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='interface_phone_number',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='تصویر رابط'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.organ', verbose_name='مرتبط به ارگان'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tel_channel',
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name='کانال تلگرام'),
        ),
        migrations.AlterField(
            model_name='galery',
            name='media',
            field=models.FileField(upload_to='gallery/logo', validators=[blog.models_validators.validate_media_extension], verbose_name='تصویر یا ویدئو'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=512, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='info',
            name='address',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1024, null=True, verbose_name='آدرس ارگان'),
        ),
        migrations.AlterField(
            model_name='info',
            name='established_year',
            field=models.DateField(blank=True, null=True, verbose_name='سال تاسیس'),
        ),
        migrations.AlterField(
            model_name='info',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='info/file', verbose_name='فایل مربوط'),
        ),
        migrations.AlterField(
            model_name='info',
            name='introduction_of_a_company',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2048, null=True, verbose_name='درباره شرکت'),
        ),
        migrations.AlterField(
            model_name='info',
            name='number_of_staff',
            field=models.PositiveIntegerField(null=True, verbose_name='تعداد کارمندان'),
        ),
        migrations.AlterField(
            model_name='info',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_company', to='blog.organ', verbose_name='مرتبط به ارگان'),
        ),
        migrations.AlterField(
            model_name='info',
            name='validation_of_knowledge_base',
            field=models.BooleanField(default=False, verbose_name='مورد تایید دانش بنیان؟'),
        ),
        migrations.AlterField(
            model_name='info',
            name='website',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='وبسایت'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='organ',
            name='activity_type',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='زمینه فعالیت'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='ceo_management_image',
            field=models.ImageField(upload_to='organization/ceo_logo', verbose_name='تصویر مدیر ارگان'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='ceo_management_name',
            field=models.CharField(max_length=128, verbose_name='نام مدیر ارگان'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت شرکت در سایت'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='gallery',
            field=models.ManyToManyField(to='blog.Galery', verbose_name='گالری'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='info',
            field=ckeditor.fields.RichTextField(blank=True, max_length=512, null=True, verbose_name='توضیحی مختصر درباره شرکت'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='is_promote',
            field=models.BooleanField(default=False, verbose_name='یک ارگان ویژه است ؟'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization/logo', verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='name',
            field=models.CharField(max_length=256, verbose_name='نام ارگان'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), blank=True, null=True, size=None, verbose_name='تگ ها'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='type',
            field=models.CharField(choices=[('CO', 'Company'), ('LB', 'Labs')], default='CO', max_length=2, verbose_name='نوع شرکت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='blog.Category', verbose_name='دسته بندی محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت محصول در سایت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gallery',
            field=models.ManyToManyField(to='blog.Galery', verbose_name='گالری'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product/image', verbose_name='عکس اصلی محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_promote',
            field=models.BooleanField(default=False, verbose_name='ویژه است ؟'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=ckeditor.fields.RichTextField(max_length=512, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.organ', verbose_name='مرتبط به ارگان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), blank=True, null=True, size=None, verbose_name='تگ های محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=2056, verbose_name='متن مرتبط به محصول'),
        ),
        migrations.AlterField(
            model_name='sitesupporter',
            name='name',
            field=ckeditor.fields.RichTextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='standards',
            name='image',
            field=models.ImageField(upload_to='standard/image', verbose_name='عکس استاندارد'),
        ),
        migrations.AlterField(
            model_name='standards',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.organ', verbose_name='مرتبط به ارگان'),
        ),
        migrations.AlterField(
            model_name='standards',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1024, null=True, verbose_name='متن مرتبط به استاندارد'),
        ),
        migrations.AlterField(
            model_name='standards',
            name='title',
            field=models.CharField(max_length=128, verbose_name='عنوان'),
        ),
    ]
