# Generated by Django 3.2.7 on 2022-01-01 13:36

import blog.models_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20220101_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='media',
            field=models.FileField(upload_to='gallery/logo', validators=[blog.models_validators.validate_media_extension]),
        ),
        migrations.AlterField(
            model_name='news',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='news/media', validators=[blog.models_validators.validate_media_extension]),
        ),
    ]
