# Generated by Django 3.2.7 on 2022-01-18 14:12

import blog.models_validators
import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20220118_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_of_submission',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت خبر در سایت'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_promote',
            field=models.BooleanField(default=False, verbose_name='ویژه است ؟'),
        ),
        migrations.AlterField(
            model_name='news',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='news/media', validators=[blog.models_validators.validate_media_extension], verbose_name='عکس یا فیلم خبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='src',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='لینک منبع خبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=2056, verbose_name='متن خبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=512, verbose_name='عنوان خبر'),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=4056, verbose_name='متنی که در صفحه قرار میگیرد'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, max_length=256, null=True, verbose_name='عنوان صفحه'),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(max_length=256, verbose_name='آدرس صفحه چه چیزی باشد ؟'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='applicant_entity_logo',
            field=models.ImageField(blank=True, null=True, upload_to='requirements/applicant_entity_image', verbose_name='لوگو سازمان درخواست کننده'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='applicant_entity_name',
            field=ckeditor.fields.RichTextField(max_length=256, verbose_name='نام سازمان درخواست کننده'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='date_of_submission',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت نیازمندی در سایت'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='deadline',
            field=models.DateField(verbose_name='تاریخ اتمام زمان نیازمندی'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='requirements/file', verbose_name='فایل مربوط به نیازمندی'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='requirements/image', verbose_name='عکس مربوط به نیازمندی'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='is_promote',
            field=models.BooleanField(default=False, verbose_name='ویژه است ؟'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=2056, verbose_name='متن نیازمندی'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=256, verbose_name='عنوان نیازمندی'),
        ),
        migrations.AlterField(
            model_name='sitesupporter',
            name='image',
            field=models.ImageField(upload_to='supporter/image', verbose_name='عکس حامی سایت'),
        ),
        migrations.AlterField(
            model_name='sitesupporter',
            name='name',
            field=ckeditor.fields.RichTextField(max_length=512, verbose_name='نام حامی سایت'),
        ),
        migrations.AlterField(
            model_name='sitesupporter',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2056, null=True, verbose_name='متن مربوطه'),
        ),
    ]
