# Generated by Django 3.2.7 on 2022-02-05 20:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20220118_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(blank=True, verbose_name='عنوان تگ')),
            ],
        ),
        migrations.AlterModelOptions(
            name='standards',
            options={'verbose_name': 'استاندارها', 'verbose_name_plural': 'استاندارهای ارگان ها '},
        ),
        migrations.AddField(
            model_name='galery',
            name='describe',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیح گالری'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='interface_phone_number',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='شماره همراه رابط'),
        ),
        migrations.RemoveField(
            model_name='organ',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='organ',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='تگ ها'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='تگ ها'),
        ),
    ]
