# Generated by Django 3.2.7 on 2022-02-06 09:55

import blog.models_validators
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, unique=True, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='gallery/logo', validators=[blog.models_validators.validate_media_extension], verbose_name='تصویر یا ویدئو')),
                ('describe', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیح گالری')),
            ],
            options={
                'verbose_name': 'گالری',
                'verbose_name_plural': 'گالری ها',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, unique=True, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'گروه ها',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(max_length=512, verbose_name='عنوان خبر')),
                ('date_of_submission', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت خبر در سایت')),
                ('text', ckeditor.fields.RichTextField(max_length=2056, verbose_name='متن خبر')),
                ('src', models.URLField(blank=True, max_length=512, null=True, verbose_name='لینک منبع خبر')),
                ('media', models.FileField(blank=True, null=True, upload_to='news/media', validators=[blog.models_validators.validate_media_extension], verbose_name='عکس یا فیلم خبر')),
                ('is_promote', models.BooleanField(default=False, verbose_name='ویژه است ؟')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
            },
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='نام ارگان')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization/logo', verbose_name='لوگو')),
                ('ceo_management_name', models.CharField(max_length=128, verbose_name='نام مدیر ارگان')),
                ('ceo_management_image', models.ImageField(upload_to='organization/ceo_logo', verbose_name='تصویر مدیر ارگان')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت شرکت در سایت')),
                ('info', ckeditor.fields.RichTextField(blank=True, max_length=512, null=True, verbose_name='توضیحی مختصر درباره شرکت')),
                ('activity_type', models.CharField(blank=True, max_length=256, null=True, verbose_name='زمینه فعالیت')),
                ('type', models.CharField(choices=[('CO', 'Company'), ('LB', 'Labs')], default='CO', max_length=2, verbose_name='نوع شرکت')),
                ('is_promote', models.BooleanField(default=False, verbose_name='یک ارگان ویژه است ؟')),
                ('gallery', models.ManyToManyField(to='blog.Galery', verbose_name='گالری')),
            ],
            options={
                'verbose_name': 'ارگان',
                'verbose_name_plural': 'ارگان ها',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(blank=True, max_length=256, null=True, verbose_name='عنوان صفحه')),
                ('text', ckeditor.fields.RichTextField(max_length=4056, verbose_name='متنی که در صفحه قرار میگیرد')),
                ('url', models.CharField(max_length=256, verbose_name='آدرس صفحه چه چیزی باشد ؟')),
            ],
            options={
                'verbose_name': 'صفحه شخصی شده',
                'verbose_name_plural': 'مجموعه صفحات شخصی سازی شده',
            },
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(max_length=256, verbose_name='عنوان نیازمندی')),
                ('text', ckeditor.fields.RichTextField(max_length=2056, verbose_name='متن نیازمندی')),
                ('applicant_entity_name', ckeditor.fields.RichTextField(max_length=256, verbose_name='نام سازمان درخواست کننده')),
                ('applicant_entity_logo', models.ImageField(blank=True, null=True, upload_to='requirements/applicant_entity_image', verbose_name='لوگو سازمان درخواست کننده')),
                ('image', models.ImageField(blank=True, null=True, upload_to='requirements/image', verbose_name='عکس مربوط به نیازمندی')),
                ('date_of_submission', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت نیازمندی در سایت')),
                ('deadline', models.DateField(verbose_name='تاریخ اتمام زمان نیازمندی')),
                ('file', models.FileField(blank=True, null=True, upload_to='requirements/file', verbose_name='فایل مربوط به نیازمندی')),
                ('is_promote', models.BooleanField(default=False, verbose_name='ویژه است ؟')),
            ],
            options={
                'verbose_name': 'نیازمندی',
                'verbose_name_plural': 'نیازمندی ها',
            },
        ),
        migrations.CreateModel(
            name='SiteSupporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ckeditor.fields.RichTextField(max_length=512, verbose_name='نام حامی سایت')),
                ('text', ckeditor.fields.RichTextField(blank=True, max_length=2056, null=True, verbose_name='متن مربوطه')),
                ('image', models.ImageField(upload_to='supporter/image', verbose_name='عکس حامی سایت')),
            ],
            options={
                'verbose_name': 'حامی سایت',
                'verbose_name_plural': 'حامیان سایت',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(blank=True, verbose_name='عنوان تگ')),
            ],
        ),
        migrations.CreateModel(
            name='Standards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='standard/image', verbose_name='عکس استاندارد')),
                ('text', ckeditor.fields.RichTextField(blank=True, max_length=1024, null=True, verbose_name='متن مرتبط به استاندارد')),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.organ', verbose_name='مرتبط به ارگان')),
            ],
            options={
                'verbose_name': 'استاندارها',
                'verbose_name_plural': 'استاندارهای ارگان ها ',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ckeditor.fields.RichTextField(max_length=512, verbose_name='نام محصول')),
                ('text', ckeditor.fields.RichTextField(max_length=2056, verbose_name='متن مرتبط به محصول')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت محصول در سایت')),
                ('image', models.ImageField(upload_to='product/image', verbose_name='عکس اصلی محصول')),
                ('is_promote', models.BooleanField(default=False, verbose_name='ویژه است ؟')),
                ('category', models.ManyToManyField(to='blog.Category', verbose_name='دسته بندی محصول')),
                ('gallery', models.ManyToManyField(to='blog.Galery', verbose_name='گالری')),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.organ', verbose_name='مرتبط به ارگان')),
                ('tags', models.ManyToManyField(to='blog.Tag', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.AddField(
            model_name='organ',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='تگ ها'),
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', ckeditor.fields.RichTextField(blank=True, max_length=1024, null=True, verbose_name='آدرس ارگان')),
                ('website', models.URLField(blank=True, max_length=512, null=True, verbose_name='وبسایت')),
                ('established_year', models.DateField(blank=True, null=True, verbose_name='سال تاسیس')),
                ('validation_of_knowledge_base', models.BooleanField(default=False, verbose_name='مورد تایید دانش بنیان؟')),
                ('introduction_of_a_company', ckeditor.fields.RichTextField(blank=True, max_length=2048, null=True, verbose_name='درباره شرکت')),
                ('number_of_staff', models.PositiveIntegerField(null=True, verbose_name='تعداد کارمندان')),
                ('file', models.FileField(blank=True, null=True, upload_to='info/file', verbose_name='فایل مربوط')),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_company', to='blog.organ', verbose_name='مرتبط به ارگان')),
            ],
            options={
                'verbose_name': 'اطلاعات ارگان',
                'verbose_name_plural': 'اطلاعات ارگان ها',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='نام رابط')),
                ('interface_phone_number', models.CharField(blank=True, max_length=18, null=True, verbose_name='شماره همراه رابط')),
                ('tel_channel', models.URLField(blank=True, max_length=256, null=True, verbose_name='کانال تلگرام')),
                ('fax', models.CharField(blank=True, max_length=18, null=True, verbose_name='فکس')),
                ('email', models.EmailField(blank=True, max_length=512, null=True, verbose_name='ایمیل')),
                ('phone_number', models.CharField(blank=True, max_length=18, null=True, verbose_name='شماره همراه')),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.organ', verbose_name='مرتبط به ارگان')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'مجموعه تماس با ما',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.group', verbose_name='گروه'),
        ),
    ]
