# Generated by Django 3.2.7 on 2022-02-07 08:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file', verbose_name='فایل')),
                ('describe', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیح فایل')),
            ],
            options={
                'verbose_name': 'فایل',
                'verbose_name_plural': 'فایل ها',
            },
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'تگ', 'verbose_name_plural': 'تگ ها'},
        ),
        migrations.AddField(
            model_name='galery',
            name='is_video',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='galery',
            name='video_poster',
            field=models.ImageField(null=True, upload_to='gallery', verbose_name='پوستر ویدئو'),
        ),
        migrations.AddField(
            model_name='news',
            name='files',
            field=models.ManyToManyField(to='blog.File', verbose_name='فایل ها'),
        ),
        migrations.AddField(
            model_name='organ',
            name='files',
            field=models.ManyToManyField(to='blog.File', verbose_name='فایل ها'),
        ),
        migrations.AddField(
            model_name='product',
            name='files',
            field=models.ManyToManyField(to='blog.File', verbose_name='فایل ها'),
        ),
    ]
