# Generated by Django 3.2.7 on 2022-02-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220207_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='video_poster',
            field=models.ImageField(blank=True, null=True, upload_to='gallery', verbose_name='پوستر ویدئو'),
        ),
    ]
