# Generated by Django 3.2.7 on 2022-02-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_galery_video_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='organ',
            old_name='logo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='organ',
            old_name='gallery',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='requirements',
            old_name='title',
            new_name='name',
        ),
    ]
