# Generated by Django 3.2.7 on 2022-02-09 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220208_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
