# Generated by Django 3.2.7 on 2022-02-09 07:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_slideshow_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='standard',
            field=models.ManyToManyField(to='blog.Standards', verbose_name='استاندارد ها'),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='media',
            field=models.FileField(default='', upload_to='slideshow/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slideshow',
            name='title',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slideshow',
            name='type',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
