# Generated by Django 3.2.7 on 2022-02-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220209_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='media',
            field=models.FileField(upload_to='slideshow'),
        ),
    ]
