# Generated by Django 3.2.7 on 2022-02-09 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20220209_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideshow',
            name='date',
        ),
    ]
