# Generated by Django 3.2.7 on 2022-02-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20220209_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='تگ ها'),
        ),
    ]
