# Generated by Django 3.2.7 on 2022-02-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_news_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='describe',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیح فایل'),
        ),
        migrations.AlterField(
            model_name='galery',
            name='describe',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیح گالری'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=512, verbose_name='عنوان خبر'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='info',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='توضیحی مختصر درباره شرکت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=512, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='name',
            field=models.CharField(max_length=256, verbose_name='عنوان نیازمندی'),
        ),
        migrations.AlterField(
            model_name='standards',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='متن مرتبط به استاندارد'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(blank=True, max_length=4096, verbose_name='عنوان تگ'),
        ),
    ]
