# Generated by Django 3.2.7 on 2022-02-10 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20220210_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='established_year',
            field=models.DateTimeField(blank=True, null=True, verbose_name='سال تاسیس'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_of_submission',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت خبر در سایت'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت شرکت در سایت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت محصول در سایت'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='date_of_submission',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت نیازمندی در سایت'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='deadline',
            field=models.DateTimeField(verbose_name='تاریخ اتمام زمان نیازمندی'),
        ),
    ]
