# Generated by Django 3.2.7 on 2022-02-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20220210_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='requirements',
            old_name='image',
            new_name='media',
        ),
        migrations.RemoveField(
            model_name='organ',
            name='image',
        ),
        migrations.AddField(
            model_name='organ',
            name='gallery',
            field=models.ManyToManyField(blank=True, to='blog.Galery', verbose_name='گالری'),
        ),
        migrations.RemoveField(
            model_name='organ',
            name='media',
        ),
        migrations.AddField(
            model_name='organ',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='organization/logo', verbose_name='لوگو'),
        ),
    ]
