# Generated by Django 3.2.7 on 2022-02-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20220212_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس ارگان'),
        ),
        migrations.AlterField(
            model_name='info',
            name='introduction_of_a_company',
            field=models.TextField(blank=True, null=True, verbose_name='درباره شرکت'),
        ),
    ]
