# Generated by Django 3.2.7 on 2022-02-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20220212_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='applicant_entity_name',
            field=models.CharField(max_length=256, verbose_name='نام سازمان درخواست کننده'),
        ),
    ]
