# Generated by Django 3.2.7 on 2022-02-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_requirements_applicant_entity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organ',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='organization/banner', verbose_name='بنر'),
        ),
    ]
