# Generated by Django 3.2.7 on 2022-02-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_organ_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='organ',
            name='category',
            field=models.ManyToManyField(blank=True, to='blog.Category'),
        ),
    ]
