# Generated by Django 3.2.7 on 2022-02-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_organ_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organ',
            name='category',
            field=models.ManyToManyField(blank=True, editable=False, to='blog.Category', verbose_name='دسته بندی ها'),
        ),
    ]
