# Generated by Django 3.2.7 on 2022-02-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20220218_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='video_poster',
            field=models.ImageField(blank=True, help_text='این فیلد موقعی استفاده میشود که یک ویدئو بارگزاری میکنید', null=True, upload_to='gallery', verbose_name='پوستر ویدئو'),
        ),
    ]
