# Generated by Django 3.2.7 on 2022-02-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_galery_video_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='media',
            field=models.FileField(blank=True, upload_to='slideshow'),
        ),
    ]
