# Generated by Django 3.2.7 on 2022-02-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_slideshow_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='company_city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='شهر محل کار شرکت'),
        ),
    ]
