# Generated by Django 3.2.7 on 2022-02-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20220218_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='organ_type',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='video_poster',
            field=models.ImageField(blank=True, upload_to='slideshow/poster'),
        ),
    ]
