# Generated by Django 3.2.7 on 2022-02-18 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20220218_1352'),
        ('blog', '0029_auto_20220218_2039'),
    ]

    operations = [
    ]
