# Generated by Django 3.2.7 on 2022-02-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20220218_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesupporter',
            name='text',
        ),
        migrations.AlterField(
            model_name='sitesupporter',
            name='name',
            field=models.CharField(max_length=512, verbose_name='نام حامی سایت'),
        ),
    ]
