# Generated by Django 3.2.7 on 2022-02-20 07:48

import ckeditor.fields
from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20220219_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=18)),
                ('fax', models.TextField()),
                ('address', models.TextField()),
                ('info', ckeditor.fields.RichTextField()),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
            ],
        ),
    ]
