# Generated by Django 3.2.7 on 2022-02-20 08:04

import ckeditor.fields
from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_aboutus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'صفحه درباره ما', 'verbose_name_plural': 'درباره ما'},
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='fax',
            field=models.TextField(verbose_name='فکس'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='info',
            field=ckeditor.fields.RichTextField(verbose_name='اطلاعات'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63, verbose_name='مکان'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='phone_number',
            field=models.CharField(max_length=18, verbose_name='شماره تلفن'),
        ),
    ]
