# Generated by Django 3.2.7 on 2022-02-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20220220_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='bale_channel',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='eata_channel',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='instagram_channel',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='telegram_channel',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='twitter_channel',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='whatsapp_channel',
            field=models.URLField(blank=True),
        ),
    ]
