# Generated by Django 3.2.7 on 2022-02-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_slideshow_organ_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organ',
            name='type',
            field=models.CharField(choices=[('CO', 'Company'), ('LB', 'Labs'), ('SC', 'Services')], default='CO', max_length=2, verbose_name='نوع شرکت'),
        ),
    ]
