# Generated by Django 3.2.7 on 2022-02-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_alter_organ_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.TextField(blank=True, null=True, verbose_name='شماره همراه'),
        ),
    ]
