# Generated by Django 3.2.7 on 2022-02-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organ',
            name='ceo_management_image',
            field=models.ImageField(blank=True, null=True, upload_to='organization/ceo_logo', verbose_name='تصویر مدیر ارگان'),
        ),
    ]
