# Generated by Django 3.2.7 on 2022-02-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_alter_organ_ceo_management_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ اتمام زمان نیازمندی'),
        ),
    ]
