# Generated by Django 3.2.7 on 2022-02-28 10:50

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_alter_requirements_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='established_year',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='سال تاسیس'),
        ),
    ]
