# Generated by Django 3.2.7 on 2022-02-28 11:40

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_alter_info_established_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_of_submission',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت خبر در سایت'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت شرکت در سایت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت محصول در سایت'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='date_of_submission',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت نیازمندی در سایت'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='deadline',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ اتمام نیازمندی'),
        ),
    ]
