# Generated by Django 3.2.7 on 2022-03-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_auto_20220301_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='established_year',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='سال تاسیس'),
        ),
    ]
