# Generated by Django 3.2.7 on 2022-03-06 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_alter_info_established_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='established_year',
        ),
    ]
