# Generated by Django 3.2.7 on 2022-03-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_remove_info_established_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='established_year',
            field=models.PositiveIntegerField(default=1400, null=True, verbose_name='سال تاسیس'),
        ),
    ]
