# Generated by Django 3.2.7 on 2022-03-14 06:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_alter_news_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='info',
            field=models.TextField(verbose_name='اطلاعات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن مرتبط به محصول'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن نیازمندی'),
        ),
    ]
