# Generated by Django 3.2.7 on 2022-03-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_auto_20220314_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='organ',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='organization/banner_logo'),
        ),
    ]
