# Generated by Django 3.2.7 on 2022-03-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_organ_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=512, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='type',
            field=models.CharField(choices=[('CO', 'Company'), ('LB', 'Labs'), ('SC', 'Services')], default='CO', max_length=2, verbose_name='نوع شرکت'),
        ),
    ]
