# Generated by Django 3.2.7 on 2022-03-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_auto_20220317_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=512, verbose_name='عنوان'),
        ),
    ]
