# Generated by Django 3.2.7 on 2022-03-30 04:52

from django.db import migrations, models
import uuid

def populate_reference(apps, schema_editor):
    MyModel = apps.get_model('blog', 'Organ')
    for obj in MyModel.objects.all():
        obj.slug = str(obj.id)
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_auto_20220317_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='organ',
            name='slug',
            field=models.TextField(default=uuid.uuid4, unique=True),
        ),
        migrations.RunPython(populate_reference),
    ]
