# Generated by Django 3.2.7 on 2022-04-04 08:28

import blog.models_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0055_auto_20220330_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='requirements',
            name='fax',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirements',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(blank=True, max_length=4096, validators=[blog.models_validators.validate_slug], verbose_name='عنوان تگ'),
        ),
    ]
