# Generated by Django 3.2.7 on 2022-03-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0054_organ_slug'),
        ('blog', '0055_auto_20220319_0006'),
    ]

    operations = [
    ]
