# Generated by Django 3.2.7 on 2022-04-04 08:33

import blog.models_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0056_auto_20220404_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organ',
            name='slug',
            field=models.TextField(blank=True, null=True, unique=True, validators=[blog.models_validators.validate_slug]),
        ),
    ]
