# Generated by Django 3.2.7 on 2022-04-04 08:36

import blog.models_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0057_alter_organ_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(blank=True, max_length=4096, validators=[blog.models_validators.validate_tag], verbose_name='عنوان تگ'),
        ),
    ]
