# Generated by Django 3.2.7 on 2022-04-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0060_auto_20220406_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='organ',
            name='group',
            field=models.ManyToManyField(blank=True, editable=False, to='blog.Group'),
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ManyToManyField(blank=True, to='blog.Group'),
        ),
    ]
