# Generated by Django 3.2.7 on 2022-04-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0061_auto_20220406_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organ',
            name='group',
        ),
    ]
