# Generated by Django 3.2.7 on 2022-04-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0062_auto_20220406_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ManyToManyField(blank=True, to='blog.Group', verbose_name='گروه ها'),
        ),
    ]
