# Generated by Django 3.2.7 on 2022-04-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0063_auto_20220406_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organ',
            name='category',
            field=models.ManyToManyField(blank=True, to='blog.Category', verbose_name='دسته بندی ها'),
        ),
    ]
